<nav aria-label="breadcrumb">

	<ol class="breadcrumb">

		<li class="breadcrumb-item"><a href="<?php echo APP_URL; ?>">Inicio</a></li>
		<li class="breadcrumb-item active" aria-current="page">Agregar</li>

	</ol>

</nav>


<div class="row">

	<div class="col-sm-12">

		<h1>Agregar liga de interés</h1>

		<hr>

		<form action="<?php echo APP_URL."tareas/agregar"; ?>" method="POST">
			

			<div class="form-group">

				<label for="nombre">Titulo</label>
				<input type="text" class="form-control" name="nombre">
			
			</div>


			<div class="form-group">

				<label for="descripcion">Descripcion</label>
				<textarea name="descripcion" class="form-control"></textarea>

			</div>

			<div class="form-group">

				<label for="fecha">Fecha</label>
				<input type="date" name="fecha" value="<?php echo date("y-m-d"); ?>" class="form-control">

			</div>

			<div class="form-group">

				<label for="link">Link</label>
				<input type="text" class="form-control" name="link">

			</div>

			<label for="categoria">Categoría</label>
			<select name="categoria_id" class="form-control">

				<?php 

					foreach ($this->categorias as $categoria) { ?>
						
						<option value="<?php echo $categoria["id"]; ?>">
							<?php echo $categoria["nombre"]; ?></option>

				<?php } ?>

			</select>
			<br>
			<br>

			<button class="btn btn-primary" type="submit">Agregar</button>

		</form>

	</div>

</div>