<nav aria-label="breadcrumb">

	<ol class="breadcrumb">

		<li class="breadcrumb-item"><a href="<?php echo APP_URL; ?>">Inicio</a></li>
		<li class="breadcrumb-item active" aria-current="page">Editar</li>
		
	</ol>

</nav>
<br>


<div class="row">

	<div class="col-sm-12">

		<h2>Editar liga de interés</h2>
		<br>

		<hr>

		<form action="<?php echo APP_URL."tareas/editar"; ?>" method="POST">

			<input type="hidden" name="id" value="<?php echo $this->tarea["id"]; ?>">
			
			<label for="nombre">Nombre</label>
			<input class="form-control" type="text" name="nombre" value="<?php echo $this->tarea["nombre"]; ?>">

			<label for="descripcion">Descripción</label>
			<textarea class="form-control" name="descripcion"><?php echo $this->tarea["descripcion"]; ?></textarea>

			<label for="fecha">Fecha</label>
			<input class="form-control" type="date" name="fecha" value="<?php echo $this->tarea["fecha"]; ?>">

			<label for="link">Link</label>
			<textarea class="form-control" name="link"><?php echo $this->tarea["link"]; ?></textarea>

			<label for="categoria">Categoría</label>
			<select class="form-control" name="categoria_id">

				<?php 

					foreach ($this->categorias as $categoria) { 

							if($this->tarea["categoria_id"]==$categoria["id"]) { ?>
						
						<option selected value="<?php echo $categoria["id"]; ?>">
							<?php echo $categoria["nombre"]; ?></option>

				<?php }else{ ?>

						<option value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["nombre"]; ?></option>

				<?php } } ?>

			</select>
			<br>
			<br>

			<button class="btn btn-primary btn-xs" type="submit" value="Guardar tarea">Guardar liga</button>

		</form>

	</div>

</div>