<nav aria-label="breadcrumb">

	<ol class="breadcrumb">

		<li class="breadcrumb-item active"><a href="<?php echo APP_URL; ?>">Inicio</a></li>
	
	</ol>

</nav>

<div class="row">

	<div class="col-sm-12">

		<h1>Administrador de ligas de interés</h1>

		<a href="<?php echo APP_URL."tareas/agregar"; ?>">

			<button type="button" class="btn btn-primary">Agregar liga</button>

		</a>

		<a href="<?php echo APP_URL."categorias/"; ?>">

			<button type="button" class="btn btn-primary">Ver categorías</button>

		</a>

		<hr>

		<div class="table-responsive">

			<table border="1" class="table table-striped table-dark">

				<tr>
					<th>ID</th>
					<th>Título</th>
					<th>Descripción</th>
					<th>Fecha</th>
					<th>Link</th>
					<th>Categoria</th>
					<th>Acción</th>
				</tr>

				<?php foreach ($this->tareas as $tarea): ?>
				
				<tr>

					<td><?php echo $tarea["tareas"]["id"]; ?></td>
					<td><?php 

						if ($tarea["tareas"]["status"]==0):

							echo "<s>".$tarea["tareas"]["nombre"]."</s>";
						
						else:
							
							echo $tarea["tareas"]["nombre"];
						
						endif;

					?></td>
					<td><?php echo $tarea["tareas"]["descripcion"]; ?></td>
					<td><?php 

						$date = date_create($tarea["tareas"]["fecha"]);
						echo date_format($date, 'd/m/y');

					?></td>
					<td><?php echo $tarea["tareas"]["link"]; ?></td>

					<td><?php echo $tarea["categorias"]["nombre"]; ?></td>

					<td>
						
						<a href="<?php echo APP_URL."tareas/editar/".$tarea["tareas"]["id"]; ?>">
							
							<button type="button" class="btn btn-light">Editar</button>

						</a>

						<br><br>
						
						<a href="<?php echo APP_URL."tareas/eliminar/".$tarea["tareas"]["id"]; ?>">
							
							<button type="button" class="btn btn-danger confirmation">Borrar</button>

						</a>

				</tr>

				<?php endforeach; ?>

			</table>

		</div>

	</div>

</div>
