<nav aria-label="breadcrumb">

	<ol class="breadcrumb">

		<li class="breadcrumb-item"><a href="<?php echo APP_URL; ?>">Inicio</a></li>
		<li class="breadcrumb-item"><a href="<?php echo APP_URL."categorias/"; ?>">Categorias</a></li>
		<li class="breadcrumb-item active" aria-current="page">Agregar</li>
		
	</ol>

</nav>



<div class="row">

	<div class="col-sm-12">

		<h1>Agregar Categoría</h1>

		<hr>

        <form action="<?php echo APP_URL."categorias/agregar"; ?>" method="POST">

            <div class="form-group">

				<label for="nombre">Nombre</label>
				<input type="text" class="form-control" name="nombre" required>
			
			</div>
             
            <button class="btn btn-primary" type="submit">Agregar</button>

        </form>

        </div>

</div>