<nav aria-label="breadcrumb">

	<ol class="breadcrumb">

		<li class="breadcrumb-item"><a href="<?php echo APP_URL; ?>">Inicio</a></li>
		<li class="breadcrumb-item active" aria-current="page">Categorías</li>
		
	</ol>

</nav>
<br>

<div class="row">

	<div class="col-sm-12">

		<h2>Lista de categorías</h2>
		<br>

        <a href="<?php echo APP_URL."categorias/agregar"; ?>">

			<button type="button" class="btn btn-primary btn-xs">Agregar categoría</button>

		</a>

        <hr>

        <div class="table-responsive">

			<table border="1" class="table table-striped table-dark">

				<tr>
					<th>ID</th>
					<th>Nombre</th>
                    <th>Acción</th>
				</tr>

                <?php foreach ($this->categorias as $categoria): ?>

                <tr>

                    <td><?php echo $categoria["id"]; ?></td>

                    <td><?php echo $categoria["nombre"]; ?></td>

                    <td>
                    
                        <a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>">
							
							<button type="button" class="btn btn-light btn-xs">Editar</button>

						</a>

                        

                        <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>">
							
							<button type="button" class="btn btn-danger btn-xs confirmation2">Eliminar</button>

						</a>
                    
                    
                    
                    </td>

                </tr>

                <?php endforeach; ?>

			</table>

		</div>

    </div>

</div>